
namespace Library_Tools.Enums
{
    public enum BooksA0
    {
        winnie_the_pooh,
        jeeves_and_wooster_stories,
        harry_potter_and_the_philosophers_stone,
        a_pretty_face,
        april_in_moscow,
        the_last_photo,
        carnival,
        sara_says_no,
        alissa,
        ski_race,
        the_well,
        the_umbrella
    }
    public enum BooksA1
    {
        island_of_dr_moreau,
        treasure_island,
        robinson_crusoe,
        the_story_of_the_treasure_seekers,
        alice_in_wonderland,
        london,
        the_mummy_returns,
        jaws,
        the_call_of_the_wild,
        the_five_orange_pips,
        a_scandal_in_bohemia,
        the_speckled_band,
        frankenstein
    }
    public enum BooksA2
    {
        life_lines,
        sky_jack,
        a_christmas_carol,
        ks_first_case,
        manchester_united,
        new_york,
        psycho,
        the_count_of_monte_cristo,
        the_canterbury_tales,
        robin_hood,
        the_pit_and_the_pendulum,
        titanic
    }
    public enum BooksB1
    {
        the_godfather,
        gulliver_travels,
        three_men_in_a_boat,
        about_a_boy,
        as_time_goes_by,
        primary_colors,
        love_actualy,
        women_in_business,
        bristol_murder,
        meet_me_in_instanbul,
        emma,
        management_gurus
    }
    public enum BooksB2
    {
        the_coral_island,
        four_weddings_and_a_funeral,
        a_time_to_kill,
        the_body_by,
        airport,
        the_phantom_of_the_opera,
        benetton,
        doctor_no,
        a_space_odyssey,
        ghost_stories,
        gold_finger,
        my_cousin_rachel,
        oliver_twist
    }
    public enum BooksC1
    {
        he_knows_too_much,
        the_gutting_of_couffignal,
        the_heroine,
        death_wish,
        ride_the_lightning,
        deadheads,
        misery,
        great_expectations,
        the_long_goodbye,
        officially_dead
    }
}
